// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmgnrYkbiuWVyQwNbNN7yho72kwJfHL0c',
    appId: '1:145751939978:web:a9b5a172a518eef67f4673',
    messagingSenderId: '145751939978',
    projectId: 'pos-aruspetshop',
    authDomain: 'pos-aruspetshop.firebaseapp.com',
    databaseURL: 'https://pos-aruspetshop-default-rtdb.firebaseio.com',
    storageBucket: 'pos-aruspetshop.appspot.com',
    measurementId: 'G-TSP35C3W4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5pEOQLduk4j6OtwwLKu0sMP7rpPxzDfk',
    appId: '1:145751939978:android:3561d426b01c8c147f4673',
    messagingSenderId: '145751939978',
    projectId: 'pos-aruspetshop',
    databaseURL: 'https://pos-aruspetshop-default-rtdb.firebaseio.com',
    storageBucket: 'pos-aruspetshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzBeymwxmf_SsyxWqVPrg6MrPLGoT02j8',
    appId: '1:145751939978:ios:a44469fc48d05f527f4673',
    messagingSenderId: '145751939978',
    projectId: 'pos-aruspetshop',
    databaseURL: 'https://pos-aruspetshop-default-rtdb.firebaseio.com',
    storageBucket: 'pos-aruspetshop.appspot.com',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzBeymwxmf_SsyxWqVPrg6MrPLGoT02j8',
    appId: '1:145751939978:ios:a44469fc48d05f527f4673',
    messagingSenderId: '145751939978',
    projectId: 'pos-aruspetshop',
    databaseURL: 'https://pos-aruspetshop-default-rtdb.firebaseio.com',
    storageBucket: 'pos-aruspetshop.appspot.com',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmgnrYkbiuWVyQwNbNN7yho72kwJfHL0c',
    appId: '1:145751939978:web:21c895edec33cf817f4673',
    messagingSenderId: '145751939978',
    projectId: 'pos-aruspetshop',
    authDomain: 'pos-aruspetshop.firebaseapp.com',
    databaseURL: 'https://pos-aruspetshop-default-rtdb.firebaseio.com',
    storageBucket: 'pos-aruspetshop.appspot.com',
    measurementId: 'G-6LTSGBLY6B',
  );

}